# Generated by Django 4.2.7 on 2024-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_settings_alter_course_level_alter_course_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Для учеников", "Для учеников"),
                    ("Для учителей", "Для учителей"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
