# Generated by Django 4.2.7 on 2024-07-24 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_alter_course_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadvideo",
            name="video",
            field=models.FileField(
                help_text="Допустимые форматы видео: mp4, mov, mkv, wmv, 3gp, f4v, avi, mp3",
                upload_to="course_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mov", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                    )
                ],
            ),
        ),
    ]
