# Generated by Django 4.2.7 on 2024-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[("Ученик", "Ученик"), ("Учитель", "Учитель")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский")],
                max_length=1,
                null=True,
            ),
        ),
    ]
